### ISSUE TITLE
Directions

### ISSUE THREAD

**Issue by ecd25** [SaturdayNeighborhoodHealthClinic/snhc-web#10]
Can we create a "Directions" page under the PATIENTS tab that has directions to each of the two clinics? Radhika and I will create a google doc of what we want it to look like (roughly).

Then there should be a link to this page pretty much anywhere we have the clinic addresses on this website.

**Comment by justinrporter** [comment]
Alright. If you (or outreach @lizmaidl ?) can decide what you want, I'll get it in there. It has to be prettier than what we had on the old site though. Old website available on request.

**Comment by lizmaidl** [comment]
i have a map that we used on the publicity/flyers... but i like embedding google maps more because then people can zoom in/out and move them around. is that an option?
i also have directions to the specialty clinics from the nearby bus stops:
From the CWE Metrolink Station:
Walk up the stairs on the west end of the platform. Turn
right towards the large fountain. Turn right again at the
roundabout (Children’s Place). The building is on the right.
From the CWE Metrobus Center:
Walk north onto Children’s Place. Take a left to head west.
The building will be on your left, just before the roundabout.

**Comment by justinrporter** [comment]
addressed by #5
